{% set name = "read5" %}
{% set version = "1.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz" # [linux64 or osx]
  sha256: affad99402294bbc3624084bba7e9e2efe985d744f5a6359cc45279945eba9f6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."
  skip: True # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py >=3.0
    - numpy >=1.20
    - pyslow5 >=1.0.0
    - ont_vbz_hdf_plugin >=1.0
    # - pod5 >=0.2.3 # currently not available in conda

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pip install pod5
    - pytest

about:
  home: https://github.com/JannesSP/read5
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "Wrapper to read fast5, slow5, blow5 and pod5 files."
  doc_url: https://github.com/JannesSP/read5.github.io
  dev_url: https://github.com/JannesSP/read5

extra:
  recipe-maintainers:
    - 38325576